version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app:rw
      - /app/node_modules
    ports:
      - "3000:3000"
