version: "3.7"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client:rw
      - /client/node_modules
    links:
      - api
    networks:
      - dwarsnetwork
    command: tail -f /dev/null
    # command: "yarn start"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=9000
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api:rw
      - /api/node_modules
    links:
      - db
    networks:
      - dwarsnetwork
    command: tail -f /dev/null
    # command: "yarn start"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      - POSTGRES_DB=database_development
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    networks:
      - dwarsnetwork
  db_gui:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
networks:
  dwarsnetwork:
    driver: bridge
