version: "3.7"
services:
  node:
    image: "node:10.15.3"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "yarn start"
