version: "3.7"
services:
  node:
    image: "node:10.15.3"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    expose:
      - "8081"
    command: "npm start"